#!/usr/bin/env bash
# Print the Homebrew formula for a release, using its prebuilt archives.
#   scripts/homebrew-formula.sh 0.2.0 dist/SHA256SUMS > Formula/mellow.rb
# This is the only source of the formula; the release workflow pushes its
# output to ritru-labs/homebrew-tap.
set -euo pipefail

version="${1:?usage: $0 VERSION SHA256SUMS}"
sums="${2:?usage: $0 VERSION SHA256SUMS}"
base="https://github.com/ritru-labs/mellow/releases/download/v$version"

sha() {
  local file="mellow-$version-$1.tar.gz" hash
  hash="$(awk -v file="$file" '$2 == file || $2 == "*" file { print $1 }' "$sums")"
  [[ "$hash" =~ ^[0-9a-f]{64}$ ]] || { echo "no checksum for $file in $sums" >&2; exit 1; }
  echo "$hash"
}

asset() {
  local hash
  hash="$(sha "$1")" || return 1
  printf '      url "%s/mellow-%s-%s.tar.gz"\n      sha256 "%s"' "$base" "$version" "$1" "$hash"
}

# Assigned first: a failure inside the here-document below would be ignored.
mac_arm="$(asset aarch64-apple-darwin)"
mac_intel="$(asset x86_64-apple-darwin)"
linux_arm="$(asset aarch64-unknown-linux-musl)"
linux_intel="$(asset x86_64-unknown-linux-musl)"

cat <<EOF
# Generated by scripts/homebrew-formula.sh in ritru-labs/mellow. Do not edit.
class Mellow < Formula
  desc "Calm terminal text editor with no modes to learn"
  homepage "https://github.com/ritru-labs/mellow"
  version "$version"
  license "Apache-2.0"

  on_macos do
    on_arm do
$mac_arm
    end
    on_intel do
$mac_intel
    end
  end

  on_linux do
    on_arm do
$linux_arm
    end
    on_intel do
$linux_intel
    end
  end

  def install
    bin.install "mellow"
  end

  test do
    assert_equal "mellow #{version}", shell_output("#{bin}/mellow --version").strip
  end
end
EOF
